services:
  postgres:
   image: postgres
   restart: always
   ports:
      - 5432
   enviroment:
      - POSTGRES_DB=mystore
      - POSTGRES_USER=alias
      - POSTGRES_PASSWORD=Alias404
   volumes:
      -./db:/var/lib/postgresql/data
