services:
  postgres:
   container_name: postgres
   image: postgres
   restart: always
   environment:
     POSTGRES_DB: ${DB_NAME}
     POSTGRES_USER: ${DB_USER}
     POSTGRES_PASSWORD: ${DB_PASSWORD}
   ports:
      - 5432:5432
   volumes:
      - ./db:/var/lib/postgresql/data

  pgadmin:
   container_name: pg_container
   image: dpage/pgadmin4
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
   ports:
      - 5050:80
